# Generated by Django 3.2.13 on 2022-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0007_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=None, related_name='ingredient', to='eateasy.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
