# Generated by Django 3.2.13 on 2022-06-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
