# Generated by Django 3.2.13 on 2022-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0002_mealplanitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplanitem',
            options={'ordering': ['day']},
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='0'),
        ),
    ]
