# Generated by Django 3.2.13 on 2022-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0005_alter_mealplanitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanitem',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='0'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save for later'), (1, 'Publish Now')], default=1),
        ),
    ]
