# Generated by Django 3.2.13 on 2022-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0006_auto_20220712_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
