# Generated by Django 3.2.13 on 2022-07-27 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eateasy', '0007_alter_recipe_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='recipe',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
