# Generated by Django 3.2.13 on 2022-07-28 20:49

from django.db import migrations, models
import eateasy.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eateasy', '0008_auto_20220727_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(validators=[eateasy.validators.textfield_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(validators=[eateasy.validators.textfield_not_empty]),
        ),
    ]
